apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgDANgpoGI243hFhG9uLpJC8V8/UiEoJNPYs0KTCQea+HJYgxUxhZhJ40+Z+PbapLVH9iHpy9y+8owfTpTIaRO+HQ2mX9YtGgGNyZWVFXbmrRV7lraVF4HrsvQVpnuaPTx2k1Lz4kMR7PpLkHIW8+rZbJa2Frd1F1wlEVGmEARGz5xJpzZ7jVGpvXiL2eUD4s4vfnR3IXwyl8iQvZOL0iy/f+YU+VCcLroI9ftBjTeY0LzJ3KTwxPa81pEVgMV/pmemDmqkpwwfpiSMjFXskASonZSjC2MPows6EoDYBZPh0dmT0rDw+XQErJ+CplTUp2IvgQSHtD8SKil1EvPb/pxYEMLWKwVOBsdygvSENjgyT9WnUkw73IeNuzlQTC/Fn1VQkyJbdeB9i786qtm/vgvnWyxoygbCBuoLpkH8hSmp+1mFxpZvynxzPO52P/T+tqZvLP6vLtdMaGfz8LGTXkKk3hYYRcGj5QWF3A8urOCJtKNn6r4C31dBJGOo62cWGcJvCIINW1xm1W0Yu+OWUYrJEJBmywTQ3+n1zn/WnUeEfwiJsgXXWQY1Yd3UBS/UkaGE08WmAWndi2R59HfNdWGxfBdL+H34pnCMcMUOWC9IQjgSkmj+3gpGlyapyhrgvrpz5QYqKCLTWQH14vQkPGAdpAIUmadioqVWhIgfwcV/nYrthO7+A86Ywn1Fl9m8u4H/W5GIzXttph9uFf70ieHLI5qwm/I1Kbqkp2uSQCkcRiQOX/+Z1Rjm6
    username: AgASJP7klW3B/6wOCSGb4N4YxRWeaIwSMMgq/KNWNfS9WToW2RJO+U9n94S+e4uR0E6HSUwC3oM3KWw2MAiiTUoXJf2aDHxrB8wyMXM5bOr9MevxSSDgHMYBwasCXIPJDVAT1KunZl1RNEU38xjkveXE9kNuBQpH9qx1WE2qrXAfaivanrXfhsYUl2PpXdYo5PBBlWgCvPmWvQcTvcuhPVgpLT3vrCv13/3FBjtno0Ojm04srIrZ8q1dHQUHMOEz9vTDXhvANlP6OG/+chPEvzyhA9daRvRXPG7tKJVCmLVmput8ZDpGr+aXp9usxNZJq5rc2pK/EuvNPaqC/p9S5ylhT7l/0LvP7ClXP2QIQt/bXfeD9U5XZLwGFUvOn08TM4tdi7Wj/IMeG5f4YKd7p2D8Tg0eqtl5G10nU0K1+u5N/yLsfICV5xFsJ7eczzNFiJltQy4OFi5+r5syF3c2D5LmvR+13vde34nbnUizWpuzy3PyWXfrVzqJ9MLkGPdmiR3RHTFaGrE8faZ+wgER/hlvs3+S6XJ/YrEFZ3sOb3nEaahpUJYlntPjTbtahC2hk9PFYr23UlJb1hr3tlVm1mFiwvf4X7AvGOWQ3GuWgs/pqoCsxoE3cCpIYyrwZF6T3yt1EEmIdMjmOo0VsE4BtX2yYAzFflQsxyD7pLumpjtla+YI7lbI1E+aKnXI64mYshEmPp1hsezwxQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

